name: salon_application
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.8
  supabase_flutter: ^2.8.4

dev_dependencies:

  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  google_fonts: ^6.2.1
  bcrypt: ^1.0.0
  provider: ^6.1.3
  animations: ^2.0.7
  intl: ^0.18.0
  image_picker: ^1.0.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  assets:
    - assets/images/onboarding1.png
    - assets/images/onboarding2.png
    - assets/images/onboarding3.png
    - assets/images/salon1.jpg
    - assets/images/salon2.jpg
    - assets/images/salon3.jpg
    - assets/images/salon4.jpg
    - assets/images/salon5.jpg


  uses-material-design: true

